behaviors:
  ShipBehavior:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 2000000
      buffer_init_steps: 5000
      tau: 0.01
      steps_per_update: 16.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 16.0
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 2.0
      gail:
        gamma: 0.99
        strength: 0.05
        learning_rate: 0.0003
        use_actions: true
        use_vail: false
        demo_path: Assets/ML-Agents/Demonstrations/ShipBehaviorDemo.demo
        network_settings:
          vis_encode_type: simple
    threaded: true
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 256
    summary_freq: 30000
#environment_parameters:
#  track_config_index:
#    curriculum:
#      - name: EasyTrack
#        value: 0.0
#        completion_criteria:
#          measure: reward
#          behavior: ShipBehavior
#          min_lesson_length: 100
#          threshold: 3.0
#          require_reset: true
#      - name: MediumTrack
#        value: 1.0
#        completion_criteria:
#          measure: reward
#          behavior: ShipBehavior
#          min_lesson_length: 100
#          threshold: 5.0
#          require_reset: true
#      - name: DefaultTrack
#        value: 2.0
env_settings:
  env_path: "Builds/Windows/Rocket Man"
  num_envs: 1
  num_areas: 16
engine_settings:
  time_scale: 20