behaviors:
  ShipBehavior:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 2000000
      buffer_init_steps: 5000
      tau: 0.01
      steps_per_update: 16.0
      save_replay_buffer: false
      init_entcoef: 0.2
      reward_signal_steps_per_update: 16.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: fully_connected
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.05
        learning_rate: 0.0003
        use_actions: false
        use_vail: true
        demo_path: Assets/ML-Agents/Demonstrations/ShipBehaviorDemo.demo
        network_settings:
          vis_encode_type: fully_connected
    threaded: true
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 30000
env_settings:
  env_path: Builds/Windows/ml-rockets
  num_envs: 1
  num_areas: 16