behaviors:
  ShipBehavior:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 2000000
      buffer_init_steps: 10000
      tau: 0.01
      steps_per_update: 16.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 16.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      deterministic: true
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.01
        learning_rate: 0.0003
        use_actions: true
        use_vail: false
        demo_path: Assets/ML-Agents/Demonstrations/ShipBehaviorDemo.demo
        network_settings:
          hidden_units: 128
          num_layers: 2
    threaded: true
    keep_checkpoints: 10
    checkpoint_interval: 2000000
    max_steps: 500000000
    time_horizon: 512
    summary_freq: 30000
environment_parameters:
  track_config_index:
    curriculum:
      - name: EasyTrack
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: ShipBehavior
          min_lesson_length: 1000
          threshold: 0.0
          require_reset: true
      - name: MediumTrack
        value: 1.0
        completion_criteria:
          measure: reward
          behavior: ShipBehavior
          min_lesson_length: 1000
          threshold: 1.0
          require_reset: true
      - name: DefaultTrack
        value: 2.0
  step_punishment:
    curriculum:
      - name: NoPunishment
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: ShipBehavior
          min_lesson_length: 1000
          threshold: 2.0
          require_reset: true
      - name: SmallPunishment
        value: -0.0001
        completion_criteria:
          measure: reward
          behavior: ShipBehavior
          min_lesson_length: 1000
          threshold: 1.5
          require_reset: true
      - name: Punishment
        value: -0.0005
  all_checkpoints_reward: 2.0
env_settings:
  env_path: "Builds/Windows/Rocket Man"
  num_envs: 1
  num_areas: 16
engine_settings:
  time_scale: 20